### ISSUE TITLE
Only takes dependencies from the input package.json

### ISSUE THREAD

**Issue by ailon** [vladshcherbin/rollup-plugin-generate-package-json#1]
Am I missing something or does it only take dependencies from the input package.json?

I assumed that the intended use case would be pruning/changing package.json from its original format to something for, say, public release. So, it would make sense to take the input file and allow modifications in it before outputting the result.

Something like what https://github.com/pmsandhu/copy-pkg-json-webpack-plugin for webpack does.

**Comment by vladshcherbin** [comment]
@ailon yes, you're right, it generates package.json from an input package.json file and an output bundle file.

The goal of the package is to generate a package.json file with only bundle dependencies. You can set *baseContents* in [options](https://github.com/vladshcherbin/rollup-plugin-generate-package-json#options) to add something to generated package.json file but there is no such functionality as in the package you linked. 

This one is similar to this - https://github.com/lostpebble/generate-package-json-webpack-plugin

**Comment by ailon** [comment]
Obviously, this can be easily worked around with something like:

```
import pkg from './package.json';
import generatePackageJson from 'rollup-plugin-generate-package-json'

let leanPkg = Object.assign({}, pkg);
leanPkg.scripts = {};
leanPkg.devDependencies = {};

...

            generatePackageJson({
                baseContents: leanPkg
              })],

```

**Comment by vladshcherbin** [comment]
@ailon so, is this a good enough solution for you or you wish I add some similar functionality here?

**Comment by ailon** [comment]
I think it is good enough for what I needed right now. You may want to add something like this to the docs though. Thanks!

**Comment by AlexeySafronov** [comment]
Hi! I have a local dependency in my package.json, like this:

```
"dependencies": {
  ...
  "react-calendar": "file:../../packages/react-calendar/react-calendar-v2.13.2.tgz",
  ...
}
```

and i want to change it's value to this variant:

```
"dependencies": {
  ...
  "react-calendar": "file:../react-calendar/react-calendar-v2.13.2.tgz",
  ...
}
```

How can i do this? Parametr "additionalDependencies" doesn't work for me.

**Comment by vladshcherbin** [comment]
@AlexeySafronov hey, I've opened [an issue](https://github.com/vladshcherbin/rollup-plugin-generate-package-json/issues/5) for this one.

I have a couple of questions:

1) your dependency is local and you want to be able change its path in generated `package.json`?
2) if 1 is yes, how would you like to do this? via `config option` or `from template package.json` (similar to proposal from this issue), but you still need to change its path though? :thinking:

If you can, please answer in linked issue. Thanks

**Comment by vladshcherbin** [comment]
@AlexeySafronov hey, I've added support for your case in 3.2.0, using `additionalDependencies`.

```js
generatePackageJson({
  additionalDependencies: {
    'react-calendar': 'file:../react-calendar/react-calendar-v2.13.2.tgz'
  }
})
```

As per initial issue, it's also now possible to use `baseContents` this way:

```js
generatePackageJson({
  baseContents: (pkg) => ({
    ...pkg,
    scripts: {},
    devDependencies: {}
  })
})
```
