### ISSUE TITLE
Rollup 1.1.x deprecation warning

### ISSUE THREAD

**Issue by dennisnewel** [vladshcherbin/rollup-plugin-generate-package-json#2]
I've just upgraded to Rollup 1.1.2 and I get the following deprecation warnings:
```
(!) generate-package-json plugin: The ongenerate hook used by plugin generate-package-json is deprecated. The generateBundle hook should be used instead.
(!) generate-package-json plugin: The onwrite hook used by plugin generate-package-json is deprecated. The generateBundle hook should be used instead.
```

Unfortunately, i couldn't quite figure out how to replace the hooks with new ones (ended up with empty json files all the time...)

**Comment by vladshcherbin** [comment]
@dennisnewel hey, thanks for the report.

I've released 3.0.0 and removed deprecated hooks. Update to see if the issue is fixed in you project.

**Comment by dennisnewel** [comment]
thanks @vladshcherbin ! 

had to update my dev environment to node 8 (should have done that anyway) but now it works like a charm! thanks for the speedy update 👏 👏

**Comment by vladshcherbin** [comment]
@dennisnewel you're welcome. This update was in my todo list so the time has come :)
