### ISSUE TITLE
Does not handle sub-path imports

### ISSUE THREAD

**Issue by gilesdring** [vladshcherbin/rollup-plugin-generate-package-json#3]
Kind of an edge case, but I was importing `uuidv4` from `uuid/v4`, and the generated package did not contain 'uuid'. The trailing `/v4` meant the matching logic was failing. There's an easy workaround in this case, but I can forsee situations where this could be problematic.

I guess truncating the dependency name from the chunk at the first path separator would do it.

**Comment by vladshcherbin** [comment]
@gilesdring hey, thanks for the report.

I've released 3.1.1, update to see if the issue is fixed in your project. 😉

**Comment by gilesdring** [comment]
Works perfectly! Thanks for the speedy response @vladshcherbin!
